import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  const [timer,setTimer] = useState(10);
  useEffect(() => {
    setTimeout(() => {
      router.push('/feedback')
    }, 10000)
   
  }, )
  setTimeout(() => {
    setTimer(timer-1)
  },1000)

  return (
  <>
   <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" >
      <div className={styles.circle}>
      {timer}
      </div>
      </div>
   
    
   
  
  </>
  )
}
